# -*- coding: utf-8 -*-

# This file is part of the Blob Inspector project
# 
# Blob Inspector project is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Blob Inspector project is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Blob Inspector project. If not, see <http://www.gnu.org/licenses/>.
#
# Author: Laurent Busson
# Version: 0.9
# Date: 2024-05-28

################################################################################
## Form generated from reading UI file 'app.ui'
##
## Created by: Qt User Interface Compiler version 6.6.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QGridLayout, QGroupBox, QHBoxLayout, QHeaderView,
    QLabel, QLineEdit, QMainWindow, QMenu,
    QMenuBar, QPushButton, QScrollArea, QSizePolicy,
    QSlider, QSpacerItem, QStackedWidget, QStatusBar,
    QTabWidget, QTableWidget, QTableWidgetItem, QVBoxLayout,
    QWidget)
import resources.resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QSize(1280, 720))
        font = QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        icon = QIcon()
        icon.addFile(u":/Icons/blob-161097_640.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.action_Load = QAction(MainWindow)
        self.action_Load.setObjectName(u"action_Load")
        icon1 = QIcon()
        icon1.addFile(u":/Icons/arrow-090.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Load.setIcon(icon1)
        self.action_SeeOptions = QAction(MainWindow)
        self.action_SeeOptions.setObjectName(u"action_SeeOptions")
        icon2 = QIcon()
        icon2.addFile(u":/Icons/equalizer.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_SeeOptions.setIcon(icon2)
        self.action_Version = QAction(MainWindow)
        self.action_Version.setObjectName(u"action_Version")
        icon3 = QIcon()
        icon3.addFile(u":/Icons/question-white.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Version.setIcon(icon3)
        self.action_Quit = QAction(MainWindow)
        self.action_Quit.setObjectName(u"action_Quit")
        icon4 = QIcon()
        icon4.addFile(u":/Icons/cross.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Quit.setIcon(icon4)
        self.action_RemoveFiles = QAction(MainWindow)
        self.action_RemoveFiles.setObjectName(u"action_RemoveFiles")
        icon5 = QIcon()
        icon5.addFile(u":/Icons/eraser.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_RemoveFiles.setIcon(icon5)
        self.action_RemoveCurrentFile = QAction(MainWindow)
        self.action_RemoveCurrentFile.setObjectName(u"action_RemoveCurrentFile")
        self.action_RemoveAllImages = QAction(MainWindow)
        self.action_RemoveAllImages.setObjectName(u"action_RemoveAllImages")
        icon6 = QIcon()
        icon6.addFile(u":/Icons/bomb.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_RemoveAllImages.setIcon(icon6)
        self.action_RemoveCurrentImage = QAction(MainWindow)
        self.action_RemoveCurrentImage.setObjectName(u"action_RemoveCurrentImage")
        self.action_RemoveCurrentImage.setIcon(icon5)
        self.action_SaveAnalysis = QAction(MainWindow)
        self.action_SaveAnalysis.setObjectName(u"action_SaveAnalysis")
        icon7 = QIcon()
        icon7.addFile(u":/Icons/drive-download.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_SaveAnalysis.setIcon(icon7)
        self.action_LoadAnalysis = QAction(MainWindow)
        self.action_LoadAnalysis.setObjectName(u"action_LoadAnalysis")
        icon8 = QIcon()
        icon8.addFile(u":/Icons/drive-upload.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_LoadAnalysis.setIcon(icon8)
        self.action_Quit_2 = QAction(MainWindow)
        self.action_Quit_2.setObjectName(u"action_Quit_2")
        self.action_Quit_2.setIcon(icon4)
        self.action_BatchAnalysis = QAction(MainWindow)
        self.action_BatchAnalysis.setObjectName(u"action_BatchAnalysis")
        icon9 = QIcon()
        icon9.addFile(u":/Icons/arrow-repeat.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_BatchAnalysis.setIcon(icon9)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setMinimumSize(QSize(1280, 674))
        self.centralwidget.setBaseSize(QSize(1280, 0))
        self.gridLayout_11 = QGridLayout(self.centralwidget)
        self.gridLayout_11.setObjectName(u"gridLayout_11")
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QSize(1262, 152))
        self.frame.setMaximumSize(QSize(16777215, 152))
        self.frame.setBaseSize(QSize(1262, 0))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_3 = QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.gb_Illumination = QGroupBox(self.frame)
        self.gb_Illumination.setObjectName(u"gb_Illumination")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Minimum)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.gb_Illumination.sizePolicy().hasHeightForWidth())
        self.gb_Illumination.setSizePolicy(sizePolicy1)
        self.gb_Illumination.setMinimumSize(QSize(0, 132))
        self.gb_Illumination.setMaximumSize(QSize(16777215, 132))
        self.gb_Illumination.setBaseSize(QSize(0, 132))
        font1 = QFont()
        font1.setPointSize(12)
        font1.setBold(True)
        self.gb_Illumination.setFont(font1)
        self.gb_Illumination.setAlignment(Qt.AlignCenter)
        self.gridLayout_7 = QGridLayout(self.gb_Illumination)
        self.gridLayout_7.setObjectName(u"gridLayout_7")
        self.pb_RollingBallRadiusToStack = QPushButton(self.gb_Illumination)
        self.pb_RollingBallRadiusToStack.setObjectName(u"pb_RollingBallRadiusToStack")
        self.pb_RollingBallRadiusToStack.setMaximumSize(QSize(120, 16777215))
        self.pb_RollingBallRadiusToStack.setBaseSize(QSize(50, 0))
        font2 = QFont()
        font2.setPointSize(10)
        font2.setBold(False)
        self.pb_RollingBallRadiusToStack.setFont(font2)

        self.gridLayout_7.addWidget(self.pb_RollingBallRadiusToStack, 2, 1, 1, 1)

        self.le_RollingBallRadius = QLineEdit(self.gb_Illumination)
        self.le_RollingBallRadius.setObjectName(u"le_RollingBallRadius")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Ignored, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.le_RollingBallRadius.sizePolicy().hasHeightForWidth())
        self.le_RollingBallRadius.setSizePolicy(sizePolicy2)
        self.le_RollingBallRadius.setMinimumSize(QSize(40, 0))
        self.le_RollingBallRadius.setMaximumSize(QSize(40, 16777215))
        font3 = QFont()
        font3.setPointSize(12)
        font3.setBold(False)
        self.le_RollingBallRadius.setFont(font3)

        self.gridLayout_7.addWidget(self.le_RollingBallRadius, 0, 2, 1, 1)

        self.pb_RollingBallRadiusView = QPushButton(self.gb_Illumination)
        self.pb_RollingBallRadiusView.setObjectName(u"pb_RollingBallRadiusView")
        self.pb_RollingBallRadiusView.setMaximumSize(QSize(120, 16777215))
        self.pb_RollingBallRadiusView.setBaseSize(QSize(50, 0))
        self.pb_RollingBallRadiusView.setFont(font2)

        self.gridLayout_7.addWidget(self.pb_RollingBallRadiusView, 2, 2, 1, 1)

        self.lb_RollingBallRadius = QLabel(self.gb_Illumination)
        self.lb_RollingBallRadius.setObjectName(u"lb_RollingBallRadius")
        self.lb_RollingBallRadius.setFont(font3)
        self.lb_RollingBallRadius.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.lb_RollingBallRadius.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.gridLayout_7.addWidget(self.lb_RollingBallRadius, 0, 0, 1, 2)

        self.pb_RollingBallRadiusToImage = QPushButton(self.gb_Illumination)
        self.pb_RollingBallRadiusToImage.setObjectName(u"pb_RollingBallRadiusToImage")
        self.pb_RollingBallRadiusToImage.setMaximumSize(QSize(120, 16777215))
        self.pb_RollingBallRadiusToImage.setBaseSize(QSize(50, 0))
        self.pb_RollingBallRadiusToImage.setFont(font2)

        self.gridLayout_7.addWidget(self.pb_RollingBallRadiusToImage, 2, 0, 1, 1)

        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.gridLayout_7.addItem(self.verticalSpacer, 1, 1, 1, 1)


        self.horizontalLayout_3.addWidget(self.gb_Illumination)

        self.gb_Segmentation = QGroupBox(self.frame)
        self.gb_Segmentation.setObjectName(u"gb_Segmentation")
        sizePolicy1.setHeightForWidth(self.gb_Segmentation.sizePolicy().hasHeightForWidth())
        self.gb_Segmentation.setSizePolicy(sizePolicy1)
        self.gb_Segmentation.setMinimumSize(QSize(0, 132))
        self.gb_Segmentation.setMaximumSize(QSize(16777215, 132))
        self.gb_Segmentation.setBaseSize(QSize(0, 132))
        font4 = QFont()
        font4.setPointSize(12)
        font4.setBold(True)
        font4.setUnderline(False)
        self.gb_Segmentation.setFont(font4)
        self.gb_Segmentation.setAlignment(Qt.AlignCenter)
        self.gridLayout = QGridLayout(self.gb_Segmentation)
        self.gridLayout.setObjectName(u"gridLayout")
        self.pb_SegmentationToImage = QPushButton(self.gb_Segmentation)
        self.pb_SegmentationToImage.setObjectName(u"pb_SegmentationToImage")
        self.pb_SegmentationToImage.setMaximumSize(QSize(120, 16777215))
        self.pb_SegmentationToImage.setBaseSize(QSize(50, 0))
        font5 = QFont()
        font5.setPointSize(10)
        font5.setBold(False)
        font5.setUnderline(False)
        self.pb_SegmentationToImage.setFont(font5)

        self.gridLayout.addWidget(self.pb_SegmentationToImage, 2, 0, 1, 1)

        self.le_ThresholdOne = QLineEdit(self.gb_Segmentation)
        self.le_ThresholdOne.setObjectName(u"le_ThresholdOne")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.le_ThresholdOne.sizePolicy().hasHeightForWidth())
        self.le_ThresholdOne.setSizePolicy(sizePolicy3)
        self.le_ThresholdOne.setMinimumSize(QSize(40, 0))
        self.le_ThresholdOne.setMaximumSize(QSize(40, 16777215))
        font6 = QFont()
        font6.setPointSize(12)
        font6.setBold(False)
        font6.setUnderline(False)
        self.le_ThresholdOne.setFont(font6)

        self.gridLayout.addWidget(self.le_ThresholdOne, 0, 2, 1, 1)

        self.le_ThresholdTwo = QLineEdit(self.gb_Segmentation)
        self.le_ThresholdTwo.setObjectName(u"le_ThresholdTwo")
        self.le_ThresholdTwo.setEnabled(False)
        sizePolicy3.setHeightForWidth(self.le_ThresholdTwo.sizePolicy().hasHeightForWidth())
        self.le_ThresholdTwo.setSizePolicy(sizePolicy3)
        self.le_ThresholdTwo.setMinimumSize(QSize(40, 0))
        self.le_ThresholdTwo.setMaximumSize(QSize(40, 16777215))
        self.le_ThresholdTwo.setFont(font6)

        self.gridLayout.addWidget(self.le_ThresholdTwo, 0, 3, 1, 1)

        self.pb_SegmentationToStack = QPushButton(self.gb_Segmentation)
        self.pb_SegmentationToStack.setObjectName(u"pb_SegmentationToStack")
        self.pb_SegmentationToStack.setMaximumSize(QSize(120, 16777215))
        self.pb_SegmentationToStack.setBaseSize(QSize(50, 0))
        self.pb_SegmentationToStack.setFont(font5)

        self.gridLayout.addWidget(self.pb_SegmentationToStack, 2, 1, 1, 1)

        self.le_BlobsDetectionMinimumRadius = QLineEdit(self.gb_Segmentation)
        self.le_BlobsDetectionMinimumRadius.setObjectName(u"le_BlobsDetectionMinimumRadius")
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Ignored)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.le_BlobsDetectionMinimumRadius.sizePolicy().hasHeightForWidth())
        self.le_BlobsDetectionMinimumRadius.setSizePolicy(sizePolicy4)
        self.le_BlobsDetectionMinimumRadius.setMinimumSize(QSize(40, 0))
        self.le_BlobsDetectionMinimumRadius.setMaximumSize(QSize(40, 16777215))
        self.le_BlobsDetectionMinimumRadius.setFont(font6)

        self.gridLayout.addWidget(self.le_BlobsDetectionMinimumRadius, 1, 2, 1, 1)

        self.pb_SegmentationView = QPushButton(self.gb_Segmentation)
        self.pb_SegmentationView.setObjectName(u"pb_SegmentationView")
        self.pb_SegmentationView.setMaximumSize(QSize(120, 16777215))
        self.pb_SegmentationView.setBaseSize(QSize(50, 0))
        self.pb_SegmentationView.setFont(font5)

        self.gridLayout.addWidget(self.pb_SegmentationView, 2, 2, 1, 2)

        self.le_BlobsDetectionMaximumRadius = QLineEdit(self.gb_Segmentation)
        self.le_BlobsDetectionMaximumRadius.setObjectName(u"le_BlobsDetectionMaximumRadius")
        sizePolicy3.setHeightForWidth(self.le_BlobsDetectionMaximumRadius.sizePolicy().hasHeightForWidth())
        self.le_BlobsDetectionMaximumRadius.setSizePolicy(sizePolicy3)
        self.le_BlobsDetectionMaximumRadius.setMinimumSize(QSize(40, 0))
        self.le_BlobsDetectionMaximumRadius.setMaximumSize(QSize(40, 16777215))
        self.le_BlobsDetectionMaximumRadius.setFont(font6)

        self.gridLayout.addWidget(self.le_BlobsDetectionMaximumRadius, 1, 3, 1, 1)

        self.combob_Threshold = QComboBox(self.gb_Segmentation)
        self.combob_Threshold.addItem("")
        self.combob_Threshold.addItem("")
        self.combob_Threshold.setObjectName(u"combob_Threshold")
        self.combob_Threshold.setFont(font6)

        self.gridLayout.addWidget(self.combob_Threshold, 0, 0, 1, 2)

        self.combob_BlobsDetection = QComboBox(self.gb_Segmentation)
        self.combob_BlobsDetection.setObjectName(u"combob_BlobsDetection")
        self.combob_BlobsDetection.setFont(font6)

        self.gridLayout.addWidget(self.combob_BlobsDetection, 1, 0, 1, 2)


        self.horizontalLayout_3.addWidget(self.gb_Segmentation)

        self.gb_Labeling = QGroupBox(self.frame)
        self.gb_Labeling.setObjectName(u"gb_Labeling")
        sizePolicy1.setHeightForWidth(self.gb_Labeling.sizePolicy().hasHeightForWidth())
        self.gb_Labeling.setSizePolicy(sizePolicy1)
        self.gb_Labeling.setMinimumSize(QSize(0, 132))
        self.gb_Labeling.setMaximumSize(QSize(16777215, 132))
        self.gb_Labeling.setBaseSize(QSize(0, 132))
        self.gb_Labeling.setFont(font1)
        self.gb_Labeling.setAlignment(Qt.AlignCenter)
        self.gridLayout_2 = QGridLayout(self.gb_Labeling)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.lb_SieveSize = QLabel(self.gb_Labeling)
        self.lb_SieveSize.setObjectName(u"lb_SieveSize")
        self.lb_SieveSize.setFont(font3)
        self.lb_SieveSize.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.gridLayout_2.addWidget(self.lb_SieveSize, 1, 0, 1, 1)

        self.le_SieveSize = QLineEdit(self.gb_Labeling)
        self.le_SieveSize.setObjectName(u"le_SieveSize")
        sizePolicy2.setHeightForWidth(self.le_SieveSize.sizePolicy().hasHeightForWidth())
        self.le_SieveSize.setSizePolicy(sizePolicy2)
        self.le_SieveSize.setMaximumSize(QSize(40, 16777215))
        self.le_SieveSize.setFont(font3)

        self.gridLayout_2.addWidget(self.le_SieveSize, 1, 1, 1, 2)

        self.pb_LabelingToImage = QPushButton(self.gb_Labeling)
        self.pb_LabelingToImage.setObjectName(u"pb_LabelingToImage")
        self.pb_LabelingToImage.setMaximumSize(QSize(120, 16777215))
        self.pb_LabelingToImage.setBaseSize(QSize(50, 0))
        self.pb_LabelingToImage.setFont(font2)

        self.gridLayout_2.addWidget(self.pb_LabelingToImage, 2, 0, 1, 1)

        self.pb_LabelingView = QPushButton(self.gb_Labeling)
        self.pb_LabelingView.setObjectName(u"pb_LabelingView")
        self.pb_LabelingView.setMaximumSize(QSize(120, 16777215))
        self.pb_LabelingView.setBaseSize(QSize(50, 0))
        self.pb_LabelingView.setFont(font2)

        self.gridLayout_2.addWidget(self.pb_LabelingView, 2, 2, 1, 1)

        self.combob_LabelingOption = QComboBox(self.gb_Labeling)
        self.combob_LabelingOption.setObjectName(u"combob_LabelingOption")
        self.combob_LabelingOption.setFont(font3)

        self.gridLayout_2.addWidget(self.combob_LabelingOption, 0, 0, 1, 3)

        self.pb_LabelingToStack = QPushButton(self.gb_Labeling)
        self.pb_LabelingToStack.setObjectName(u"pb_LabelingToStack")
        self.pb_LabelingToStack.setMaximumSize(QSize(120, 16777215))
        self.pb_LabelingToStack.setBaseSize(QSize(50, 0))
        self.pb_LabelingToStack.setFont(font2)

        self.gridLayout_2.addWidget(self.pb_LabelingToStack, 2, 1, 1, 1)


        self.horizontalLayout_3.addWidget(self.gb_Labeling)

        self.gb_Contours = QGroupBox(self.frame)
        self.gb_Contours.setObjectName(u"gb_Contours")
        sizePolicy1.setHeightForWidth(self.gb_Contours.sizePolicy().hasHeightForWidth())
        self.gb_Contours.setSizePolicy(sizePolicy1)
        self.gb_Contours.setMinimumSize(QSize(0, 132))
        self.gb_Contours.setMaximumSize(QSize(16777215, 132))
        self.gb_Contours.setBaseSize(QSize(0, 132))
        self.gb_Contours.setFont(font1)
        self.gb_Contours.setAlignment(Qt.AlignCenter)
        self.gridLayout_3 = QGridLayout(self.gb_Contours)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.combob_Contours = QComboBox(self.gb_Contours)
        self.combob_Contours.setObjectName(u"combob_Contours")
        sizePolicy5 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.combob_Contours.sizePolicy().hasHeightForWidth())
        self.combob_Contours.setSizePolicy(sizePolicy5)
        self.combob_Contours.setMinimumSize(QSize(40, 0))
        self.combob_Contours.setFont(font3)

        self.gridLayout_3.addWidget(self.combob_Contours, 1, 0, 1, 8)

        self.pb_ContoursView = QPushButton(self.gb_Contours)
        self.pb_ContoursView.setObjectName(u"pb_ContoursView")
        self.pb_ContoursView.setMaximumSize(QSize(120, 16777215))
        self.pb_ContoursView.setBaseSize(QSize(50, 0))
        self.pb_ContoursView.setFont(font2)

        self.gridLayout_3.addWidget(self.pb_ContoursView, 4, 5, 1, 3)

        self.lb_BackgroundThreshold = QLabel(self.gb_Contours)
        self.lb_BackgroundThreshold.setObjectName(u"lb_BackgroundThreshold")
        sizePolicy6 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Preferred)
        sizePolicy6.setHorizontalStretch(0)
        sizePolicy6.setVerticalStretch(0)
        sizePolicy6.setHeightForWidth(self.lb_BackgroundThreshold.sizePolicy().hasHeightForWidth())
        self.lb_BackgroundThreshold.setSizePolicy(sizePolicy6)
        self.lb_BackgroundThreshold.setMinimumSize(QSize(0, 0))
        self.lb_BackgroundThreshold.setFont(font3)
        self.lb_BackgroundThreshold.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.gridLayout_3.addWidget(self.lb_BackgroundThreshold, 2, 0, 1, 2)

        self.pb_ContoursToStack = QPushButton(self.gb_Contours)
        self.pb_ContoursToStack.setObjectName(u"pb_ContoursToStack")
        self.pb_ContoursToStack.setMaximumSize(QSize(120, 16777215))
        self.pb_ContoursToStack.setBaseSize(QSize(50, 0))
        self.pb_ContoursToStack.setFont(font2)

        self.gridLayout_3.addWidget(self.pb_ContoursToStack, 4, 2, 1, 3)

        self.le_BackgroundThreshold = QLineEdit(self.gb_Contours)
        self.le_BackgroundThreshold.setObjectName(u"le_BackgroundThreshold")
        sizePolicy2.setHeightForWidth(self.le_BackgroundThreshold.sizePolicy().hasHeightForWidth())
        self.le_BackgroundThreshold.setSizePolicy(sizePolicy2)
        self.le_BackgroundThreshold.setMinimumSize(QSize(40, 0))
        self.le_BackgroundThreshold.setMaximumSize(QSize(40, 16777215))
        self.le_BackgroundThreshold.setFont(font3)

        self.gridLayout_3.addWidget(self.le_BackgroundThreshold, 2, 2, 1, 1)

        self.pb_ContoursToImage = QPushButton(self.gb_Contours)
        self.pb_ContoursToImage.setObjectName(u"pb_ContoursToImage")
        self.pb_ContoursToImage.setMaximumSize(QSize(120, 16777215))
        self.pb_ContoursToImage.setBaseSize(QSize(50, 0))
        self.pb_ContoursToImage.setFont(font2)

        self.gridLayout_3.addWidget(self.pb_ContoursToImage, 4, 0, 1, 2)

        self.le_ContoursMinSize = QLineEdit(self.gb_Contours)
        self.le_ContoursMinSize.setObjectName(u"le_ContoursMinSize")
        sizePolicy2.setHeightForWidth(self.le_ContoursMinSize.sizePolicy().hasHeightForWidth())
        self.le_ContoursMinSize.setSizePolicy(sizePolicy2)
        self.le_ContoursMinSize.setMinimumSize(QSize(40, 0))
        self.le_ContoursMinSize.setMaximumSize(QSize(40, 16777215))
        self.le_ContoursMinSize.setFont(font3)

        self.gridLayout_3.addWidget(self.le_ContoursMinSize, 2, 6, 1, 1)

        self.la_ContoursMinSize = QLabel(self.gb_Contours)
        self.la_ContoursMinSize.setObjectName(u"la_ContoursMinSize")
        sizePolicy6.setHeightForWidth(self.la_ContoursMinSize.sizePolicy().hasHeightForWidth())
        self.la_ContoursMinSize.setSizePolicy(sizePolicy6)
        self.la_ContoursMinSize.setMinimumSize(QSize(0, 0))
        self.la_ContoursMinSize.setFont(font3)
        self.la_ContoursMinSize.setLayoutDirection(Qt.LeftToRight)
        self.la_ContoursMinSize.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.gridLayout_3.addWidget(self.la_ContoursMinSize, 2, 4, 1, 2)


        self.horizontalLayout_3.addWidget(self.gb_Contours)

        self.gb_Density = QGroupBox(self.frame)
        self.gb_Density.setObjectName(u"gb_Density")
        sizePolicy1.setHeightForWidth(self.gb_Density.sizePolicy().hasHeightForWidth())
        self.gb_Density.setSizePolicy(sizePolicy1)
        self.gb_Density.setMinimumSize(QSize(0, 132))
        self.gb_Density.setMaximumSize(QSize(16777215, 132))
        self.gb_Density.setBaseSize(QSize(0, 132))
        self.gb_Density.setFont(font1)
        self.gb_Density.setAlignment(Qt.AlignCenter)
        self.gridLayout_4 = QGridLayout(self.gb_Density)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.pb_DensityToStack = QPushButton(self.gb_Density)
        self.pb_DensityToStack.setObjectName(u"pb_DensityToStack")
        self.pb_DensityToStack.setMaximumSize(QSize(120, 16777215))
        self.pb_DensityToStack.setBaseSize(QSize(50, 0))
        self.pb_DensityToStack.setFont(font2)

        self.gridLayout_4.addWidget(self.pb_DensityToStack, 4, 1, 1, 1)

        self.lb_Kernel = QLabel(self.gb_Density)
        self.lb_Kernel.setObjectName(u"lb_Kernel")
        self.lb_Kernel.setFont(font3)
        self.lb_Kernel.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.gridLayout_4.addWidget(self.lb_Kernel, 0, 0, 1, 2)

        self.lb_Layers = QLabel(self.gb_Density)
        self.lb_Layers.setObjectName(u"lb_Layers")
        self.lb_Layers.setFont(font3)
        self.lb_Layers.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.gridLayout_4.addWidget(self.lb_Layers, 2, 0, 1, 2)

        self.pb_DensityToImage = QPushButton(self.gb_Density)
        self.pb_DensityToImage.setObjectName(u"pb_DensityToImage")
        self.pb_DensityToImage.setMaximumSize(QSize(120, 16777215))
        self.pb_DensityToImage.setBaseSize(QSize(50, 0))
        self.pb_DensityToImage.setFont(font2)

        self.gridLayout_4.addWidget(self.pb_DensityToImage, 4, 0, 1, 1)

        self.pb_DensityView = QPushButton(self.gb_Density)
        self.pb_DensityView.setObjectName(u"pb_DensityView")
        self.pb_DensityView.setMaximumSize(QSize(120, 16777215))
        self.pb_DensityView.setBaseSize(QSize(50, 0))
        self.pb_DensityView.setFont(font2)

        self.gridLayout_4.addWidget(self.pb_DensityView, 4, 2, 1, 1)

        self.le_DensityTargetLayers = QLineEdit(self.gb_Density)
        self.le_DensityTargetLayers.setObjectName(u"le_DensityTargetLayers")
        sizePolicy2.setHeightForWidth(self.le_DensityTargetLayers.sizePolicy().hasHeightForWidth())
        self.le_DensityTargetLayers.setSizePolicy(sizePolicy2)
        self.le_DensityTargetLayers.setMinimumSize(QSize(40, 0))
        self.le_DensityTargetLayers.setMaximumSize(QSize(40, 16777215))
        self.le_DensityTargetLayers.setFont(font3)

        self.gridLayout_4.addWidget(self.le_DensityTargetLayers, 2, 2, 1, 1)

        self.le_DensityMapKernelSize = QLineEdit(self.gb_Density)
        self.le_DensityMapKernelSize.setObjectName(u"le_DensityMapKernelSize")
        sizePolicy2.setHeightForWidth(self.le_DensityMapKernelSize.sizePolicy().hasHeightForWidth())
        self.le_DensityMapKernelSize.setSizePolicy(sizePolicy2)
        self.le_DensityMapKernelSize.setMinimumSize(QSize(40, 0))
        self.le_DensityMapKernelSize.setMaximumSize(QSize(40, 16777215))
        self.le_DensityMapKernelSize.setFont(font3)

        self.gridLayout_4.addWidget(self.le_DensityMapKernelSize, 0, 2, 1, 1)


        self.horizontalLayout_3.addWidget(self.gb_Density)

        self.gb_Results = QGroupBox(self.frame)
        self.gb_Results.setObjectName(u"gb_Results")
        sizePolicy1.setHeightForWidth(self.gb_Results.sizePolicy().hasHeightForWidth())
        self.gb_Results.setSizePolicy(sizePolicy1)
        self.gb_Results.setMinimumSize(QSize(0, 132))
        self.gb_Results.setMaximumSize(QSize(16777215, 132))
        self.gb_Results.setBaseSize(QSize(0, 132))
        self.gb_Results.setFont(font1)
        self.gb_Results.setAlignment(Qt.AlignCenter)
        self.gridLayout_5 = QGridLayout(self.gb_Results)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.label_3 = QLabel(self.gb_Results)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setFont(font2)
        self.label_3.setAlignment(Qt.AlignCenter)

        self.gridLayout_5.addWidget(self.label_3, 0, 3, 1, 1)

        self.le_InterZ = QLineEdit(self.gb_Results)
        self.le_InterZ.setObjectName(u"le_InterZ")
        sizePolicy3.setHeightForWidth(self.le_InterZ.sizePolicy().hasHeightForWidth())
        self.le_InterZ.setSizePolicy(sizePolicy3)
        self.le_InterZ.setMaximumSize(QSize(100, 16777215))
        self.le_InterZ.setBaseSize(QSize(50, 0))
        self.le_InterZ.setFont(font3)
        self.le_InterZ.setAlignment(Qt.AlignCenter)

        self.gridLayout_5.addWidget(self.le_InterZ, 2, 2, 1, 1)

        self.le_ZThickness = QLineEdit(self.gb_Results)
        self.le_ZThickness.setObjectName(u"le_ZThickness")
        sizePolicy3.setHeightForWidth(self.le_ZThickness.sizePolicy().hasHeightForWidth())
        self.le_ZThickness.setSizePolicy(sizePolicy3)
        self.le_ZThickness.setMaximumSize(QSize(100, 16777215))
        self.le_ZThickness.setBaseSize(QSize(50, 0))
        self.le_ZThickness.setFont(font3)
        self.le_ZThickness.setAlignment(Qt.AlignCenter)

        self.gridLayout_5.addWidget(self.le_ZThickness, 2, 1, 1, 1)

        self.label = QLabel(self.gb_Results)
        self.label.setObjectName(u"label")
        self.label.setFont(font2)
        self.label.setAlignment(Qt.AlignCenter)

        self.gridLayout_5.addWidget(self.label, 0, 1, 1, 1)

        self.le_PixelSize = QLineEdit(self.gb_Results)
        self.le_PixelSize.setObjectName(u"le_PixelSize")
        sizePolicy3.setHeightForWidth(self.le_PixelSize.sizePolicy().hasHeightForWidth())
        self.le_PixelSize.setSizePolicy(sizePolicy3)
        self.le_PixelSize.setMaximumSize(QSize(100, 16777215))
        self.le_PixelSize.setBaseSize(QSize(50, 0))
        self.le_PixelSize.setFont(font3)
        self.le_PixelSize.setAlignment(Qt.AlignCenter)

        self.gridLayout_5.addWidget(self.le_PixelSize, 2, 3, 1, 1)

        self.label_2 = QLabel(self.gb_Results)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setFont(font2)
        self.label_2.setAlignment(Qt.AlignCenter)

        self.gridLayout_5.addWidget(self.label_2, 0, 2, 1, 1)

        self.pb_ResultsView = QPushButton(self.gb_Results)
        self.pb_ResultsView.setObjectName(u"pb_ResultsView")
        sizePolicy5.setHeightForWidth(self.pb_ResultsView.sizePolicy().hasHeightForWidth())
        self.pb_ResultsView.setSizePolicy(sizePolicy5)
        self.pb_ResultsView.setFont(font2)

        self.gridLayout_5.addWidget(self.pb_ResultsView, 3, 3, 1, 1)

        self.pb_ResultsApplyToStacks = QPushButton(self.gb_Results)
        self.pb_ResultsApplyToStacks.setObjectName(u"pb_ResultsApplyToStacks")
        self.pb_ResultsApplyToStacks.setFont(font2)

        self.gridLayout_5.addWidget(self.pb_ResultsApplyToStacks, 3, 1, 1, 2)


        self.horizontalLayout_3.addWidget(self.gb_Results)


        self.gridLayout_11.addWidget(self.frame, 0, 0, 1, 1)

        self.sw_Data = QStackedWidget(self.centralwidget)
        self.sw_Data.setObjectName(u"sw_Data")
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.verticalLayout_2 = QVBoxLayout(self.page)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.frame_2 = QFrame(self.page)
        self.frame_2.setObjectName(u"frame_2")
        sizePolicy7 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy7.setHorizontalStretch(0)
        sizePolicy7.setVerticalStretch(0)
        sizePolicy7.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy7)
        self.frame_2.setMinimumSize(QSize(1262, 90))
        self.frame_2.setMaximumSize(QSize(16777215, 90))
        self.frame_2.setBaseSize(QSize(0, 0))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.gridLayout_6 = QGridLayout(self.frame_2)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.wi_OriginalText = QWidget(self.frame_2)
        self.wi_OriginalText.setObjectName(u"wi_OriginalText")
        self.wi_OriginalText.setEnabled(True)
        sizePolicy7.setHeightForWidth(self.wi_OriginalText.sizePolicy().hasHeightForWidth())
        self.wi_OriginalText.setSizePolicy(sizePolicy7)
        self.wi_OriginalText.setMinimumSize(QSize(400, 70))
        self.wi_OriginalText.setMaximumSize(QSize(16777215, 70))
        self.wi_OriginalText.setBaseSize(QSize(0, 0))
        self.layout_Text_Original = QGridLayout(self.wi_OriginalText)
        self.layout_Text_Original.setObjectName(u"layout_Text_Original")
        self.pb_Histogram = QPushButton(self.wi_OriginalText)
        self.pb_Histogram.setObjectName(u"pb_Histogram")
        font7 = QFont()
        font7.setPointSize(10)
        self.pb_Histogram.setFont(font7)

        self.layout_Text_Original.addWidget(self.pb_Histogram, 2, 6, 1, 1)

        self.lb_SliceNumber = QLabel(self.wi_OriginalText)
        self.lb_SliceNumber.setObjectName(u"lb_SliceNumber")
        sizePolicy5.setHeightForWidth(self.lb_SliceNumber.sizePolicy().hasHeightForWidth())
        self.lb_SliceNumber.setSizePolicy(sizePolicy5)
        self.lb_SliceNumber.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.layout_Text_Original.addWidget(self.lb_SliceNumber, 2, 4, 1, 1)

        self.cb_IncludeImage = QCheckBox(self.wi_OriginalText)
        self.cb_IncludeImage.setObjectName(u"cb_IncludeImage")
        sizePolicy3.setHeightForWidth(self.cb_IncludeImage.sizePolicy().hasHeightForWidth())
        self.cb_IncludeImage.setSizePolicy(sizePolicy3)
        self.cb_IncludeImage.setLayoutDirection(Qt.RightToLeft)

        self.layout_Text_Original.addWidget(self.cb_IncludeImage, 2, 5, 1, 1)

        self.hs_SliceNumber = QSlider(self.wi_OriginalText)
        self.hs_SliceNumber.setObjectName(u"hs_SliceNumber")
        sizePolicy5.setHeightForWidth(self.hs_SliceNumber.sizePolicy().hasHeightForWidth())
        self.hs_SliceNumber.setSizePolicy(sizePolicy5)
        self.hs_SliceNumber.setPageStep(1)
        self.hs_SliceNumber.setOrientation(Qt.Horizontal)
        self.hs_SliceNumber.setTickPosition(QSlider.NoTicks)
        self.hs_SliceNumber.setTickInterval(1)

        self.layout_Text_Original.addWidget(self.hs_SliceNumber, 2, 0, 1, 4)

        self.cb_Scale = QCheckBox(self.wi_OriginalText)
        self.cb_Scale.setObjectName(u"cb_Scale")
        self.cb_Scale.setLayoutDirection(Qt.RightToLeft)

        self.layout_Text_Original.addWidget(self.cb_Scale, 2, 7, 1, 1)

        self.combob_FileName = QComboBox(self.wi_OriginalText)
        self.combob_FileName.setObjectName(u"combob_FileName")

        self.layout_Text_Original.addWidget(self.combob_FileName, 0, 0, 1, 8)


        self.gridLayout_6.addWidget(self.wi_OriginalText, 0, 0, 1, 1)

        self.wi_Image2Text = QWidget(self.frame_2)
        self.wi_Image2Text.setObjectName(u"wi_Image2Text")
        sizePolicy3.setHeightForWidth(self.wi_Image2Text.sizePolicy().hasHeightForWidth())
        self.wi_Image2Text.setSizePolicy(sizePolicy3)
        self.wi_Image2Text.setMinimumSize(QSize(400, 70))
        self.wi_Image2Text.setMaximumSize(QSize(16777215, 70))
        self.wi_Image2Text.setBaseSize(QSize(0, 0))
        self.layout_Text2 = QGridLayout(self.wi_Image2Text)
        self.layout_Text2.setObjectName(u"layout_Text2")
        self.horizontalSpacer_3 = QSpacerItem(20, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.layout_Text2.addItem(self.horizontalSpacer_3, 1, 1, 1, 1)

        self.horizontalSpacer = QSpacerItem(20, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.layout_Text2.addItem(self.horizontalSpacer, 0, 1, 1, 1)

        self.lb_X = QLabel(self.wi_Image2Text)
        self.lb_X.setObjectName(u"lb_X")
        sizePolicy3.setHeightForWidth(self.lb_X.sizePolicy().hasHeightForWidth())
        self.lb_X.setSizePolicy(sizePolicy3)
        self.lb_X.setMaximumSize(QSize(15, 16777215))
        self.lb_X.setBaseSize(QSize(15, 0))

        self.layout_Text2.addWidget(self.lb_X, 1, 2, 1, 1)

        self.le_CentroidX = QLineEdit(self.wi_Image2Text)
        self.le_CentroidX.setObjectName(u"le_CentroidX")
        sizePolicy5.setHeightForWidth(self.le_CentroidX.sizePolicy().hasHeightForWidth())
        self.le_CentroidX.setSizePolicy(sizePolicy5)
        self.le_CentroidX.setMaximumSize(QSize(63, 16777215))
        self.le_CentroidX.setBaseSize(QSize(63, 0))
        self.le_CentroidX.setFont(font)

        self.layout_Text2.addWidget(self.le_CentroidX, 1, 3, 1, 1)

        self.lb_CentroidCoordinates = QLabel(self.wi_Image2Text)
        self.lb_CentroidCoordinates.setObjectName(u"lb_CentroidCoordinates")
        self.lb_CentroidCoordinates.setFont(font)
        self.lb_CentroidCoordinates.setAlignment(Qt.AlignCenter)

        self.layout_Text2.addWidget(self.lb_CentroidCoordinates, 0, 2, 1, 4)

        self.horizontalSpacer_4 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.layout_Text2.addItem(self.horizontalSpacer_4, 1, 6, 1, 2)

        self.lb_Y = QLabel(self.wi_Image2Text)
        self.lb_Y.setObjectName(u"lb_Y")
        sizePolicy3.setHeightForWidth(self.lb_Y.sizePolicy().hasHeightForWidth())
        self.lb_Y.setSizePolicy(sizePolicy3)
        self.lb_Y.setMaximumSize(QSize(15, 16777215))
        self.lb_Y.setBaseSize(QSize(15, 0))

        self.layout_Text2.addWidget(self.lb_Y, 1, 4, 1, 1)

        self.pb_CentroidAuto = QPushButton(self.wi_Image2Text)
        self.pb_CentroidAuto.setObjectName(u"pb_CentroidAuto")
        sizePolicy8 = QSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Fixed)
        sizePolicy8.setHorizontalStretch(0)
        sizePolicy8.setVerticalStretch(0)
        sizePolicy8.setHeightForWidth(self.pb_CentroidAuto.sizePolicy().hasHeightForWidth())
        self.pb_CentroidAuto.setSizePolicy(sizePolicy8)
        self.pb_CentroidAuto.setMaximumSize(QSize(70, 16777215))
        self.pb_CentroidAuto.setBaseSize(QSize(63, 0))
        font8 = QFont()
        font8.setPointSize(11)
        self.pb_CentroidAuto.setFont(font8)

        self.layout_Text2.addWidget(self.pb_CentroidAuto, 0, 6, 1, 1)

        self.le_CentroidY = QLineEdit(self.wi_Image2Text)
        self.le_CentroidY.setObjectName(u"le_CentroidY")
        sizePolicy5.setHeightForWidth(self.le_CentroidY.sizePolicy().hasHeightForWidth())
        self.le_CentroidY.setSizePolicy(sizePolicy5)
        self.le_CentroidY.setMaximumSize(QSize(63, 16777215))
        self.le_CentroidY.setBaseSize(QSize(63, 0))
        self.le_CentroidY.setFont(font)

        self.layout_Text2.addWidget(self.le_CentroidY, 1, 5, 1, 1)

        self.cb_MainSlice = QCheckBox(self.wi_Image2Text)
        self.cb_MainSlice.setObjectName(u"cb_MainSlice")

        self.layout_Text2.addWidget(self.cb_MainSlice, 1, 8, 1, 1)

        self.horizontalSpacer_2 = QSpacerItem(20, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.layout_Text2.addItem(self.horizontalSpacer_2, 0, 7, 1, 2)


        self.gridLayout_6.addWidget(self.wi_Image2Text, 0, 3, 1, 1)

        self.wi_Image1Text = QWidget(self.frame_2)
        self.wi_Image1Text.setObjectName(u"wi_Image1Text")
        sizePolicy3.setHeightForWidth(self.wi_Image1Text.sizePolicy().hasHeightForWidth())
        self.wi_Image1Text.setSizePolicy(sizePolicy3)
        self.wi_Image1Text.setMinimumSize(QSize(400, 70))
        self.wi_Image1Text.setMaximumSize(QSize(16777215, 70))
        self.wi_Image1Text.setBaseSize(QSize(0, 0))
        self.layout_Text1 = QGridLayout(self.wi_Image1Text)
        self.layout_Text1.setObjectName(u"layout_Text1")
        self.combob_cmap = QComboBox(self.wi_Image1Text)
        self.combob_cmap.setObjectName(u"combob_cmap")
        self.combob_cmap.setMinimumSize(QSize(100, 0))
        self.combob_cmap.setMaximumSize(QSize(200, 16777215))

        self.layout_Text1.addWidget(self.combob_cmap, 1, 1, 1, 1)

        self.lb_MapStats = QLabel(self.wi_Image1Text)
        self.lb_MapStats.setObjectName(u"lb_MapStats")
        self.lb_MapStats.setFont(font8)
        self.lb_MapStats.setAlignment(Qt.AlignCenter)

        self.layout_Text1.addWidget(self.lb_MapStats, 0, 0, 2, 1)

        self.lb_TargetStats = QLabel(self.wi_Image1Text)
        self.lb_TargetStats.setObjectName(u"lb_TargetStats")
        self.lb_TargetStats.setFont(font8)
        self.lb_TargetStats.setAlignment(Qt.AlignCenter)

        self.layout_Text1.addWidget(self.lb_TargetStats, 0, 4, 2, 1)

        self.cb_SharedColorBar = QCheckBox(self.wi_Image1Text)
        self.cb_SharedColorBar.setObjectName(u"cb_SharedColorBar")

        self.layout_Text1.addWidget(self.cb_SharedColorBar, 1, 2, 1, 1)

        self.combob_DensityDisplay = QComboBox(self.wi_Image1Text)
        self.combob_DensityDisplay.addItem("")
        self.combob_DensityDisplay.addItem("")
        self.combob_DensityDisplay.addItem("")
        self.combob_DensityDisplay.addItem("")
        self.combob_DensityDisplay.setObjectName(u"combob_DensityDisplay")
        self.combob_DensityDisplay.setMinimumSize(QSize(100, 0))
        self.combob_DensityDisplay.setMaximumSize(QSize(200, 16777215))

        self.layout_Text1.addWidget(self.combob_DensityDisplay, 0, 1, 1, 2)


        self.gridLayout_6.addWidget(self.wi_Image1Text, 0, 1, 1, 1)


        self.verticalLayout_2.addWidget(self.frame_2)

        self.frame_3 = QFrame(self.page)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.horizontalLayout = QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.wi_OriginalImage = QWidget(self.frame_3)
        self.wi_OriginalImage.setObjectName(u"wi_OriginalImage")
        self.wi_OriginalImage.setMinimumSize(QSize(408, 0))
        self.layout_Original = QVBoxLayout(self.wi_OriginalImage)
        self.layout_Original.setObjectName(u"layout_Original")

        self.horizontalLayout.addWidget(self.wi_OriginalImage)

        self.wi_Image1Canvas = QWidget(self.frame_3)
        self.wi_Image1Canvas.setObjectName(u"wi_Image1Canvas")
        self.wi_Image1Canvas.setMinimumSize(QSize(408, 0))
        self.wi_Image1Canvas.setBaseSize(QSize(0, 0))
        self.layout_Image1 = QVBoxLayout(self.wi_Image1Canvas)
        self.layout_Image1.setObjectName(u"layout_Image1")

        self.horizontalLayout.addWidget(self.wi_Image1Canvas)

        self.wi_Image2Canvas = QWidget(self.frame_3)
        self.wi_Image2Canvas.setObjectName(u"wi_Image2Canvas")
        self.wi_Image2Canvas.setMinimumSize(QSize(408, 0))
        self.wi_Image2Canvas.setBaseSize(QSize(0, 0))
        self.wi_Image2Canvas.setFont(font)
        self.layout_Image2 = QVBoxLayout(self.wi_Image2Canvas)
        self.layout_Image2.setObjectName(u"layout_Image2")

        self.horizontalLayout.addWidget(self.wi_Image2Canvas)


        self.verticalLayout_2.addWidget(self.frame_3)

        self.sw_Data.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.verticalLayout_4 = QVBoxLayout(self.page_2)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.tabWidget = QTabWidget(self.page_2)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tab_1 = QWidget()
        self.tab_1.setObjectName(u"tab_1")
        self.verticalLayout = QVBoxLayout(self.tab_1)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.scrollArea = QScrollArea(self.tab_1)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 98, 89))
        self.verticalLayout_3 = QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.tw_Count = QTableWidget(self.scrollAreaWidgetContents)
        self.tw_Count.setObjectName(u"tw_Count")

        self.verticalLayout_3.addWidget(self.tw_Count)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.verticalLayout.addWidget(self.scrollArea)

        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.verticalLayout_7 = QVBoxLayout(self.tab_2)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.scrollArea_2 = QScrollArea(self.tab_2)
        self.scrollArea_2.setObjectName(u"scrollArea_2")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollAreaWidgetContents_2 = QWidget()
        self.scrollAreaWidgetContents_2.setObjectName(u"scrollAreaWidgetContents_2")
        self.scrollAreaWidgetContents_2.setGeometry(QRect(0, 0, 98, 89))
        self.verticalLayout_5 = QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.tw_Density = QTableWidget(self.scrollAreaWidgetContents_2)
        self.tw_Density.setObjectName(u"tw_Density")

        self.verticalLayout_5.addWidget(self.tw_Density)

        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)

        self.verticalLayout_7.addWidget(self.scrollArea_2)

        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.verticalLayout_8 = QVBoxLayout(self.tab_3)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.scrollArea_3 = QScrollArea(self.tab_3)
        self.scrollArea_3.setObjectName(u"scrollArea_3")
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollAreaWidgetContents_3 = QWidget()
        self.scrollAreaWidgetContents_3.setObjectName(u"scrollAreaWidgetContents_3")
        self.scrollAreaWidgetContents_3.setGeometry(QRect(0, 0, 98, 89))
        self.verticalLayout_6 = QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.tw_Distance = QTableWidget(self.scrollAreaWidgetContents_3)
        self.tw_Distance.setObjectName(u"tw_Distance")

        self.verticalLayout_6.addWidget(self.tw_Distance)

        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)

        self.verticalLayout_8.addWidget(self.scrollArea_3)

        self.tabWidget.addTab(self.tab_3, "")

        self.verticalLayout_4.addWidget(self.tabWidget)

        self.gb_ResultsChoice = QGroupBox(self.page_2)
        self.gb_ResultsChoice.setObjectName(u"gb_ResultsChoice")
        self.gb_ResultsChoice.setFont(font1)
        self.gb_ResultsChoice.setAlignment(Qt.AlignCenter)
        self.gridLayout_8 = QGridLayout(self.gb_ResultsChoice)
        self.gridLayout_8.setObjectName(u"gridLayout_8")
        self.cb_ResultsDistanceSpecificCentroid = QCheckBox(self.gb_ResultsChoice)
        self.cb_ResultsDistanceSpecificCentroid.setObjectName(u"cb_ResultsDistanceSpecificCentroid")
        self.cb_ResultsDistanceSpecificCentroid.setFont(font3)

        self.gridLayout_8.addWidget(self.cb_ResultsDistanceSpecificCentroid, 0, 6, 1, 1)

        self.cb_ResultsDensityCount = QCheckBox(self.gb_ResultsChoice)
        self.cb_ResultsDensityCount.setObjectName(u"cb_ResultsDensityCount")
        self.cb_ResultsDensityCount.setFont(font3)

        self.gridLayout_8.addWidget(self.cb_ResultsDensityCount, 0, 4, 1, 1)

        self.pb_ResultsNone = QPushButton(self.gb_ResultsChoice)
        self.pb_ResultsNone.setObjectName(u"pb_ResultsNone")
        self.pb_ResultsNone.setMinimumSize(QSize(50, 0))
        self.pb_ResultsNone.setMaximumSize(QSize(80, 16777215))
        self.pb_ResultsNone.setBaseSize(QSize(50, 0))
        self.pb_ResultsNone.setFont(font3)

        self.gridLayout_8.addWidget(self.pb_ResultsNone, 0, 1, 1, 1)

        self.pb_ResultsAll = QPushButton(self.gb_ResultsChoice)
        self.pb_ResultsAll.setObjectName(u"pb_ResultsAll")
        self.pb_ResultsAll.setMinimumSize(QSize(50, 0))
        self.pb_ResultsAll.setMaximumSize(QSize(80, 16777215))
        self.pb_ResultsAll.setBaseSize(QSize(50, 0))
        self.pb_ResultsAll.setFont(font3)

        self.gridLayout_8.addWidget(self.pb_ResultsAll, 0, 0, 1, 1)

        self.cb_ResultsCount = QCheckBox(self.gb_ResultsChoice)
        self.cb_ResultsCount.setObjectName(u"cb_ResultsCount")
        self.cb_ResultsCount.setFont(font3)

        self.gridLayout_8.addWidget(self.cb_ResultsCount, 0, 2, 1, 1)

        self.cb_ResultsDistanceOwnCentroid = QCheckBox(self.gb_ResultsChoice)
        self.cb_ResultsDistanceOwnCentroid.setObjectName(u"cb_ResultsDistanceOwnCentroid")
        self.cb_ResultsDistanceOwnCentroid.setFont(font3)

        self.gridLayout_8.addWidget(self.cb_ResultsDistanceOwnCentroid, 0, 8, 1, 1)

        self.cb_ResultsDensityPercentage = QCheckBox(self.gb_ResultsChoice)
        self.cb_ResultsDensityPercentage.setObjectName(u"cb_ResultsDensityPercentage")
        self.cb_ResultsDensityPercentage.setFont(font3)

        self.gridLayout_8.addWidget(self.cb_ResultsDensityPercentage, 0, 3, 1, 1)

        self.cb_ResultsDensitySize = QCheckBox(self.gb_ResultsChoice)
        self.cb_ResultsDensitySize.setObjectName(u"cb_ResultsDensitySize")
        self.cb_ResultsDensitySize.setFont(font3)

        self.gridLayout_8.addWidget(self.cb_ResultsDensitySize, 0, 5, 1, 1)


        self.verticalLayout_4.addWidget(self.gb_ResultsChoice)

        self.frame_4 = QFrame(self.page_2)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.gridLayout_10 = QGridLayout(self.frame_4)
        self.gridLayout_10.setObjectName(u"gridLayout_10")
        self.pb_ResultsDestinationFolder = QPushButton(self.frame_4)
        self.pb_ResultsDestinationFolder.setObjectName(u"pb_ResultsDestinationFolder")
        self.pb_ResultsDestinationFolder.setMaximumSize(QSize(150, 16777215))

        self.gridLayout_10.addWidget(self.pb_ResultsDestinationFolder, 0, 2, 1, 1)

        self.lb_ResultsCSVFileName = QLabel(self.frame_4)
        self.lb_ResultsCSVFileName.setObjectName(u"lb_ResultsCSVFileName")
        self.lb_ResultsCSVFileName.setAlignment(Qt.AlignCenter)

        self.gridLayout_10.addWidget(self.lb_ResultsCSVFileName, 0, 4, 1, 1)

        self.horizontalSpacer_9 = QSpacerItem(20, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.gridLayout_10.addItem(self.horizontalSpacer_9, 0, 3, 1, 1)

        self.le_ResultsCSVFileName = QLineEdit(self.frame_4)
        self.le_ResultsCSVFileName.setObjectName(u"le_ResultsCSVFileName")
        sizePolicy5.setHeightForWidth(self.le_ResultsCSVFileName.sizePolicy().hasHeightForWidth())
        self.le_ResultsCSVFileName.setSizePolicy(sizePolicy5)
        self.le_ResultsCSVFileName.setMinimumSize(QSize(300, 0))
        self.le_ResultsCSVFileName.setMaximumSize(QSize(350, 16777215))

        self.gridLayout_10.addWidget(self.le_ResultsCSVFileName, 1, 4, 1, 1)

        self.lb_ResultsDestinationFolder = QLabel(self.frame_4)
        self.lb_ResultsDestinationFolder.setObjectName(u"lb_ResultsDestinationFolder")
        sizePolicy9 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred)
        sizePolicy9.setHorizontalStretch(0)
        sizePolicy9.setVerticalStretch(0)
        sizePolicy9.setHeightForWidth(self.lb_ResultsDestinationFolder.sizePolicy().hasHeightForWidth())
        self.lb_ResultsDestinationFolder.setSizePolicy(sizePolicy9)
        self.lb_ResultsDestinationFolder.setAlignment(Qt.AlignCenter)

        self.gridLayout_10.addWidget(self.lb_ResultsDestinationFolder, 1, 1, 1, 3)

        self.horizontalSpacer_8 = QSpacerItem(20, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.gridLayout_10.addItem(self.horizontalSpacer_8, 0, 1, 1, 1)

        self.pb_ResultsBack = QPushButton(self.frame_4)
        self.pb_ResultsBack.setObjectName(u"pb_ResultsBack")

        self.gridLayout_10.addWidget(self.pb_ResultsBack, 0, 0, 2, 1)

        self.pb_ResultsSave = QPushButton(self.frame_4)
        self.pb_ResultsSave.setObjectName(u"pb_ResultsSave")
        self.pb_ResultsSave.setMaximumSize(QSize(100, 16777215))
        self.pb_ResultsSave.setFont(font3)

        self.gridLayout_10.addWidget(self.pb_ResultsSave, 0, 5, 2, 1)


        self.verticalLayout_4.addWidget(self.frame_4)

        self.sw_Data.addWidget(self.page_2)

        self.gridLayout_11.addWidget(self.sw_Data, 1, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QRect(0, 0, 1280, 27))
        self.menu_File = QMenu(self.menubar)
        self.menu_File.setObjectName(u"menu_File")
        self.menu_Options = QMenu(self.menubar)
        self.menu_Options.setObjectName(u"menu_Options")
        self.menu_About = QMenu(self.menubar)
        self.menu_About.setObjectName(u"menu_About")
        self.menu_Process = QMenu(self.menubar)
        self.menu_Process.setObjectName(u"menu_Process")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.le_RollingBallRadius, self.pb_RollingBallRadiusToImage)
        QWidget.setTabOrder(self.pb_RollingBallRadiusToImage, self.pb_RollingBallRadiusToStack)
        QWidget.setTabOrder(self.pb_RollingBallRadiusToStack, self.pb_RollingBallRadiusView)
        QWidget.setTabOrder(self.pb_RollingBallRadiusView, self.combob_Threshold)
        QWidget.setTabOrder(self.combob_Threshold, self.le_ThresholdOne)
        QWidget.setTabOrder(self.le_ThresholdOne, self.le_ThresholdTwo)
        QWidget.setTabOrder(self.le_ThresholdTwo, self.combob_BlobsDetection)
        QWidget.setTabOrder(self.combob_BlobsDetection, self.le_BlobsDetectionMinimumRadius)
        QWidget.setTabOrder(self.le_BlobsDetectionMinimumRadius, self.le_BlobsDetectionMaximumRadius)
        QWidget.setTabOrder(self.le_BlobsDetectionMaximumRadius, self.pb_SegmentationToImage)
        QWidget.setTabOrder(self.pb_SegmentationToImage, self.pb_SegmentationToStack)
        QWidget.setTabOrder(self.pb_SegmentationToStack, self.pb_SegmentationView)
        QWidget.setTabOrder(self.pb_SegmentationView, self.combob_LabelingOption)
        QWidget.setTabOrder(self.combob_LabelingOption, self.le_SieveSize)
        QWidget.setTabOrder(self.le_SieveSize, self.pb_LabelingToImage)
        QWidget.setTabOrder(self.pb_LabelingToImage, self.pb_LabelingToStack)
        QWidget.setTabOrder(self.pb_LabelingToStack, self.pb_LabelingView)
        QWidget.setTabOrder(self.pb_LabelingView, self.combob_Contours)
        QWidget.setTabOrder(self.combob_Contours, self.le_BackgroundThreshold)
        QWidget.setTabOrder(self.le_BackgroundThreshold, self.le_ContoursMinSize)
        QWidget.setTabOrder(self.le_ContoursMinSize, self.pb_ContoursToImage)
        QWidget.setTabOrder(self.pb_ContoursToImage, self.pb_ContoursToStack)
        QWidget.setTabOrder(self.pb_ContoursToStack, self.pb_ContoursView)
        QWidget.setTabOrder(self.pb_ContoursView, self.le_DensityMapKernelSize)
        QWidget.setTabOrder(self.le_DensityMapKernelSize, self.le_DensityTargetLayers)
        QWidget.setTabOrder(self.le_DensityTargetLayers, self.pb_DensityToImage)
        QWidget.setTabOrder(self.pb_DensityToImage, self.pb_DensityToStack)
        QWidget.setTabOrder(self.pb_DensityToStack, self.pb_DensityView)
        QWidget.setTabOrder(self.pb_DensityView, self.le_ZThickness)
        QWidget.setTabOrder(self.le_ZThickness, self.le_InterZ)
        QWidget.setTabOrder(self.le_InterZ, self.le_PixelSize)
        QWidget.setTabOrder(self.le_PixelSize, self.pb_ResultsApplyToStacks)
        QWidget.setTabOrder(self.pb_ResultsApplyToStacks, self.pb_ResultsView)
        QWidget.setTabOrder(self.pb_ResultsView, self.combob_FileName)
        QWidget.setTabOrder(self.combob_FileName, self.hs_SliceNumber)
        QWidget.setTabOrder(self.hs_SliceNumber, self.cb_IncludeImage)
        QWidget.setTabOrder(self.cb_IncludeImage, self.pb_Histogram)
        QWidget.setTabOrder(self.pb_Histogram, self.cb_Scale)
        QWidget.setTabOrder(self.cb_Scale, self.combob_DensityDisplay)
        QWidget.setTabOrder(self.combob_DensityDisplay, self.combob_cmap)
        QWidget.setTabOrder(self.combob_cmap, self.cb_SharedColorBar)
        QWidget.setTabOrder(self.cb_SharedColorBar, self.le_CentroidX)
        QWidget.setTabOrder(self.le_CentroidX, self.le_CentroidY)
        QWidget.setTabOrder(self.le_CentroidY, self.pb_CentroidAuto)
        QWidget.setTabOrder(self.pb_CentroidAuto, self.cb_MainSlice)
        QWidget.setTabOrder(self.cb_MainSlice, self.tabWidget)
        QWidget.setTabOrder(self.tabWidget, self.scrollArea_2)
        QWidget.setTabOrder(self.scrollArea_2, self.scrollArea)
        QWidget.setTabOrder(self.scrollArea, self.pb_ResultsAll)
        QWidget.setTabOrder(self.pb_ResultsAll, self.pb_ResultsNone)
        QWidget.setTabOrder(self.pb_ResultsNone, self.cb_ResultsCount)
        QWidget.setTabOrder(self.cb_ResultsCount, self.cb_ResultsDensityPercentage)
        QWidget.setTabOrder(self.cb_ResultsDensityPercentage, self.cb_ResultsDensityCount)
        QWidget.setTabOrder(self.cb_ResultsDensityCount, self.cb_ResultsDistanceSpecificCentroid)
        QWidget.setTabOrder(self.cb_ResultsDistanceSpecificCentroid, self.cb_ResultsDistanceOwnCentroid)
        QWidget.setTabOrder(self.cb_ResultsDistanceOwnCentroid, self.pb_ResultsDestinationFolder)
        QWidget.setTabOrder(self.pb_ResultsDestinationFolder, self.le_ResultsCSVFileName)
        QWidget.setTabOrder(self.le_ResultsCSVFileName, self.pb_ResultsSave)
        QWidget.setTabOrder(self.pb_ResultsSave, self.tw_Distance)
        QWidget.setTabOrder(self.tw_Distance, self.tw_Density)
        QWidget.setTabOrder(self.tw_Density, self.scrollArea_3)
        QWidget.setTabOrder(self.scrollArea_3, self.tw_Count)
        QWidget.setTabOrder(self.tw_Count, self.cb_ResultsDensitySize)
        QWidget.setTabOrder(self.cb_ResultsDensitySize, self.pb_ResultsBack)

        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Process.menuAction())
        self.menubar.addAction(self.menu_Options.menuAction())
        self.menubar.addAction(self.menu_About.menuAction())
        self.menu_File.addAction(self.action_Load)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_RemoveAllImages)
        self.menu_File.addAction(self.action_RemoveCurrentImage)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_SaveAnalysis)
        self.menu_File.addAction(self.action_LoadAnalysis)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Quit_2)
        self.menu_Options.addAction(self.action_SeeOptions)
        self.menu_About.addAction(self.action_Version)
        self.menu_Process.addAction(self.action_BatchAnalysis)

        self.retranslateUi(MainWindow)

        self.sw_Data.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Blob inspector v0.9", None))
        self.action_Load.setText(QCoreApplication.translate("MainWindow", u"&Load images", None))
        self.action_SeeOptions.setText(QCoreApplication.translate("MainWindow", u"&Profiles", None))
        self.action_Version.setText(QCoreApplication.translate("MainWindow", u"&Version", None))
        self.action_Quit.setText(QCoreApplication.translate("MainWindow", u"Quit", None))
        self.action_RemoveFiles.setText(QCoreApplication.translate("MainWindow", u"Remove files", None))
        self.action_RemoveCurrentFile.setText(QCoreApplication.translate("MainWindow", u"Remove current file", None))
        self.action_RemoveAllImages.setText(QCoreApplication.translate("MainWindow", u"Remove &all stacks", None))
#if QT_CONFIG(tooltip)
        self.action_RemoveAllImages.setToolTip(QCoreApplication.translate("MainWindow", u"Remove all files", None))
#endif // QT_CONFIG(tooltip)
        self.action_RemoveCurrentImage.setText(QCoreApplication.translate("MainWindow", u"Remove &current stack", None))
        self.action_SaveAnalysis.setText(QCoreApplication.translate("MainWindow", u"&Save analysis", None))
#if QT_CONFIG(tooltip)
        self.action_SaveAnalysis.setToolTip(QCoreApplication.translate("MainWindow", u"Save the current analysis", None))
#endif // QT_CONFIG(tooltip)
        self.action_LoadAnalysis.setText(QCoreApplication.translate("MainWindow", u"Load &analysis", None))
#if QT_CONFIG(tooltip)
        self.action_LoadAnalysis.setToolTip(QCoreApplication.translate("MainWindow", u"Load data from a saved analyis", None))
#endif // QT_CONFIG(tooltip)
        self.action_Quit_2.setText(QCoreApplication.translate("MainWindow", u"&Quit", None))
#if QT_CONFIG(tooltip)
        self.action_Quit_2.setToolTip(QCoreApplication.translate("MainWindow", u"Quit", None))
#endif // QT_CONFIG(tooltip)
        self.action_BatchAnalysis.setText(QCoreApplication.translate("MainWindow", u"&Batch analysis", None))
#if QT_CONFIG(tooltip)
        self.action_BatchAnalysis.setToolTip(QCoreApplication.translate("MainWindow", u"Analyse all stacks of images.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.gb_Illumination.setToolTip(QCoreApplication.translate("MainWindow", u"Correct uneven illumination with the rolling ball algorithm.", None))
#endif // QT_CONFIG(tooltip)
        self.gb_Illumination.setTitle(QCoreApplication.translate("MainWindow", u"ILLUMINATION", None))
        self.pb_RollingBallRadiusToStack.setText(QCoreApplication.translate("MainWindow", u"Apply to stack", None))
#if QT_CONFIG(tooltip)
        self.le_RollingBallRadius.setToolTip(QCoreApplication.translate("MainWindow", u"Input the rolling ball radius in pixels", None))
#endif // QT_CONFIG(tooltip)
        self.pb_RollingBallRadiusView.setText(QCoreApplication.translate("MainWindow", u"View", None))
#if QT_CONFIG(tooltip)
        self.lb_RollingBallRadius.setToolTip(QCoreApplication.translate("MainWindow", u"Input the rolling ball radius in pixels", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.lb_RollingBallRadius.setStatusTip("")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.lb_RollingBallRadius.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.lb_RollingBallRadius.setText(QCoreApplication.translate("MainWindow", u"Rolling ball radius", None))
        self.pb_RollingBallRadiusToImage.setText(QCoreApplication.translate("MainWindow", u"Apply to image", None))
#if QT_CONFIG(tooltip)
        self.gb_Segmentation.setToolTip(QCoreApplication.translate("MainWindow", u"Segment objects (blobs) based on threshold(s) value(s) (compulsory) and blobs detection algorithms (optional).", None))
#endif // QT_CONFIG(tooltip)
        self.gb_Segmentation.setTitle(QCoreApplication.translate("MainWindow", u"SEGMENTATION", None))
        self.pb_SegmentationToImage.setText(QCoreApplication.translate("MainWindow", u"Apply to image", None))
#if QT_CONFIG(tooltip)
        self.le_ThresholdOne.setToolTip(QCoreApplication.translate("MainWindow", u"Input the value of the threshold from 0 to 255 or from 0 to 1.", u"Input the value of the threshold either from 0 to 255 or from 0 to 1."))
#endif // QT_CONFIG(tooltip)
        self.le_ThresholdOne.setText(QCoreApplication.translate("MainWindow", u"I", None))
#if QT_CONFIG(tooltip)
        self.le_ThresholdTwo.setToolTip(QCoreApplication.translate("MainWindow", u"Input the value of the second threshold from 0 to 255 or from 0 to 1. The value must be less than the one of the first threshold.", None))
#endif // QT_CONFIG(tooltip)
        self.le_ThresholdTwo.setText(QCoreApplication.translate("MainWindow", u"II", None))
        self.pb_SegmentationToStack.setText(QCoreApplication.translate("MainWindow", u"Apply to stack", None))
#if QT_CONFIG(tooltip)
        self.le_BlobsDetectionMinimumRadius.setToolTip(QCoreApplication.translate("MainWindow", u"Input the minimum value of the blobs radius in pixels. Smaller blobs won't be detected.", None))
#endif // QT_CONFIG(tooltip)
        self.le_BlobsDetectionMinimumRadius.setText(QCoreApplication.translate("MainWindow", u"min", None))
        self.pb_SegmentationView.setText(QCoreApplication.translate("MainWindow", u"View", None))
#if QT_CONFIG(tooltip)
        self.le_BlobsDetectionMaximumRadius.setToolTip(QCoreApplication.translate("MainWindow", u"Input the maximum value of the blobs radius in pixels. Bigger blobs won't be detected.", None))
#endif // QT_CONFIG(tooltip)
        self.le_BlobsDetectionMaximumRadius.setText(QCoreApplication.translate("MainWindow", u"max", None))
        self.combob_Threshold.setItemText(0, QCoreApplication.translate("MainWindow", u"One threshold", None))
        self.combob_Threshold.setItemText(1, QCoreApplication.translate("MainWindow", u"Two thresholds", None))

#if QT_CONFIG(tooltip)
        self.combob_Threshold.setToolTip(QCoreApplication.translate("MainWindow", u"Choose thresholding option.", None))
#endif // QT_CONFIG(tooltip)
        self.combob_Threshold.setCurrentText(QCoreApplication.translate("MainWindow", u"One threshold", None))
#if QT_CONFIG(tooltip)
        self.combob_BlobsDetection.setToolTip(QCoreApplication.translate("MainWindow", u"Laplacian of Gaussian (LoG), Difference of Gaussian (DoG), Determinant of Hessian (DoH)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.gb_Labeling.setToolTip(QCoreApplication.translate("MainWindow", u"Identifies individual objects (blobs) with or without watershed algorithm.", None))
#endif // QT_CONFIG(tooltip)
        self.gb_Labeling.setTitle(QCoreApplication.translate("MainWindow", u"LABELING", None))
#if QT_CONFIG(tooltip)
        self.lb_SieveSize.setToolTip(QCoreApplication.translate("MainWindow", u"Input the size of the sieve in pixels. Objects with a size strictly above the sieve size will be kept.", None))
#endif // QT_CONFIG(tooltip)
        self.lb_SieveSize.setText(QCoreApplication.translate("MainWindow", u"Sieve size", None))
#if QT_CONFIG(tooltip)
        self.le_SieveSize.setToolTip(QCoreApplication.translate("MainWindow", u"Input the size of the sieve in pixels. Objects with a size strictly above the sieve size will be kept.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.pb_LabelingToImage.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.pb_LabelingToImage.setText(QCoreApplication.translate("MainWindow", u"Apply to image", None))
        self.pb_LabelingView.setText(QCoreApplication.translate("MainWindow", u"View", None))
#if QT_CONFIG(tooltip)
        self.combob_LabelingOption.setToolTip(QCoreApplication.translate("MainWindow", u"Choose the labeling option.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.pb_LabelingToStack.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.pb_LabelingToStack.setText(QCoreApplication.translate("MainWindow", u"Apply to stack", None))
#if QT_CONFIG(tooltip)
        self.gb_Contours.setToolTip(QCoreApplication.translate("MainWindow", u"Determine the contour of the object containing the blobs. ", None))
#endif // QT_CONFIG(tooltip)
        self.gb_Contours.setTitle(QCoreApplication.translate("MainWindow", u"SHAPE CONTOURS", None))
#if QT_CONFIG(tooltip)
        self.combob_Contours.setToolTip(QCoreApplication.translate("MainWindow", u"Choose the algorithm to contour the object containing the blobs.", None))
#endif // QT_CONFIG(tooltip)
        self.pb_ContoursView.setText(QCoreApplication.translate("MainWindow", u"View", None))
#if QT_CONFIG(tooltip)
        self.lb_BackgroundThreshold.setToolTip(QCoreApplication.translate("MainWindow", u"Input the minimum value of the background. Pixels with a value strictly over the threshold will be considered part of the object depending on the algorithm.", None))
#endif // QT_CONFIG(tooltip)
        self.lb_BackgroundThreshold.setText(QCoreApplication.translate("MainWindow", u"Threshold", None))
        self.pb_ContoursToStack.setText(QCoreApplication.translate("MainWindow", u"Apply to stack", None))
#if QT_CONFIG(tooltip)
        self.le_BackgroundThreshold.setToolTip(QCoreApplication.translate("MainWindow", u"Input the minimum value of the background. Pixels with a value strictly over the threshold will be considered part of the object depending on the algorithm.", None))
#endif // QT_CONFIG(tooltip)
        self.pb_ContoursToImage.setText(QCoreApplication.translate("MainWindow", u"Apply to image", None))
#if QT_CONFIG(tooltip)
        self.le_ContoursMinSize.setToolTip(QCoreApplication.translate("MainWindow", u"Choose the minimum size in pixels of the contoured objects.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.la_ContoursMinSize.setToolTip(QCoreApplication.translate("MainWindow", u"Choose the minimum size in pixels of the contoured objects.", None))
#endif // QT_CONFIG(tooltip)
        self.la_ContoursMinSize.setText(QCoreApplication.translate("MainWindow", u"Min size", None))
#if QT_CONFIG(tooltip)
        self.gb_Density.setToolTip(QCoreApplication.translate("MainWindow", u"Calculate the density of blobs in the contoured object.", None))
#endif // QT_CONFIG(tooltip)
        self.gb_Density.setTitle(QCoreApplication.translate("MainWindow", u"DENSITY", None))
        self.pb_DensityToStack.setText(QCoreApplication.translate("MainWindow", u"Apply to stack", None))
#if QT_CONFIG(tooltip)
        self.lb_Kernel.setToolTip(QCoreApplication.translate("MainWindow", u"Input the kernel size in pixels. Choose an odd number.", None))
#endif // QT_CONFIG(tooltip)
        self.lb_Kernel.setText(QCoreApplication.translate("MainWindow", u"Heatmap kernel size", None))
#if QT_CONFIG(tooltip)
        self.lb_Layers.setToolTip(QCoreApplication.translate("MainWindow", u"Input the number of concentric regions (layers) around the centroid of the contoured object.", None))
#endif // QT_CONFIG(tooltip)
        self.lb_Layers.setText(QCoreApplication.translate("MainWindow", u"Target layers", None))
        self.pb_DensityToImage.setText(QCoreApplication.translate("MainWindow", u"Apply to image", None))
        self.pb_DensityView.setText(QCoreApplication.translate("MainWindow", u"View", None))
#if QT_CONFIG(tooltip)
        self.le_DensityTargetLayers.setToolTip(QCoreApplication.translate("MainWindow", u"Input the number of concentric regions (layers) around the centroid of the contoured object.", None))
#endif // QT_CONFIG(tooltip)
        self.le_DensityTargetLayers.setText("")
#if QT_CONFIG(tooltip)
        self.le_DensityMapKernelSize.setToolTip(QCoreApplication.translate("MainWindow", u"Input the kernel size in pixels. Choose an odd number.", None))
#endif // QT_CONFIG(tooltip)
        self.le_DensityMapKernelSize.setText("")
#if QT_CONFIG(tooltip)
        self.gb_Results.setToolTip(QCoreApplication.translate("MainWindow", u"Display the results. The option will be available if all the selected images in the stack have been processed.", None))
#endif // QT_CONFIG(tooltip)
        self.gb_Results.setTitle(QCoreApplication.translate("MainWindow", u"RESULTS", None))
#if QT_CONFIG(tooltip)
        self.label_3.setToolTip(QCoreApplication.translate("MainWindow", u"Input the size of a pixel. Choose the same unit for the 3 parameters in the results section.", None))
#endif // QT_CONFIG(tooltip)
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Pixel size", None))
#if QT_CONFIG(tooltip)
        self.le_InterZ.setToolTip(QCoreApplication.translate("MainWindow", u"Input the distance between each slice. Choose the same unit for the 3 parameters in the results section.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.le_ZThickness.setToolTip(QCoreApplication.translate("MainWindow", u"Input the thickness of each slice. Choose the same unit for the 3 parameters in the results section.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.label.setToolTip(QCoreApplication.translate("MainWindow", u"Input the thickness of each slice. Choose the same unit for the 3 parameters in the results section.", None))
#endif // QT_CONFIG(tooltip)
        self.label.setText(QCoreApplication.translate("MainWindow", u"Slice thickness", None))
#if QT_CONFIG(tooltip)
        self.le_PixelSize.setToolTip(QCoreApplication.translate("MainWindow", u"Input the size of a pixel. Choose the same unit for the 3 parameters in the results section.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.label_2.setToolTip(QCoreApplication.translate("MainWindow", u"Input the distance between each slice. Choose the same unit for the 3 parameters in the results section.", None))
#endif // QT_CONFIG(tooltip)
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Interslice space", None))
#if QT_CONFIG(tooltip)
        self.pb_ResultsView.setToolTip(QCoreApplication.translate("MainWindow", u"View results of the current stack.", None))
#endif // QT_CONFIG(tooltip)
        self.pb_ResultsView.setText(QCoreApplication.translate("MainWindow", u"View", None))
#if QT_CONFIG(tooltip)
        self.pb_ResultsApplyToStacks.setToolTip(QCoreApplication.translate("MainWindow", u"Apply the microscope acquisition parameters to all the stacks.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pb_ResultsApplyToStacks.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.pb_ResultsApplyToStacks.setText(QCoreApplication.translate("MainWindow", u"Apply to stacks", None))
#if QT_CONFIG(tooltip)
        self.pb_Histogram.setToolTip(QCoreApplication.translate("MainWindow", u"Call a window with the histogram of the image(s).", None))
#endif // QT_CONFIG(tooltip)
        self.pb_Histogram.setText(QCoreApplication.translate("MainWindow", u"Histogram", None))
#if QT_CONFIG(tooltip)
        self.lb_SliceNumber.setToolTip(QCoreApplication.translate("MainWindow", u"Slice in the stack.", None))
#endif // QT_CONFIG(tooltip)
        self.lb_SliceNumber.setText("")
#if QT_CONFIG(tooltip)
        self.cb_IncludeImage.setToolTip(QCoreApplication.translate("MainWindow", u"If unchecked, the image will be excluded from the results.", None))
#endif // QT_CONFIG(tooltip)
        self.cb_IncludeImage.setText(QCoreApplication.translate("MainWindow", u"Include", None))
#if QT_CONFIG(tooltip)
        self.hs_SliceNumber.setToolTip(QCoreApplication.translate("MainWindow", u"Slice in the stack.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.cb_Scale.setToolTip(QCoreApplication.translate("MainWindow", u"Will display a scale on images provided scale options and pixel size are input.", None))
#endif // QT_CONFIG(tooltip)
        self.cb_Scale.setText(QCoreApplication.translate("MainWindow", u"Scale", None))
#if QT_CONFIG(tooltip)
        self.combob_FileName.setToolTip(QCoreApplication.translate("MainWindow", u"Filename.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.lb_X.setToolTip(QCoreApplication.translate("MainWindow", u"X coordinate of the centroid of the contoured object.", None))
#endif // QT_CONFIG(tooltip)
        self.lb_X.setText(QCoreApplication.translate("MainWindow", u"X", None))
#if QT_CONFIG(tooltip)
        self.le_CentroidX.setToolTip(QCoreApplication.translate("MainWindow", u"X coordinate of the centroid of the contoured object.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.lb_CentroidCoordinates.setToolTip(QCoreApplication.translate("MainWindow", u"Coordinates of the centroid of the contoured object.", None))
#endif // QT_CONFIG(tooltip)
        self.lb_CentroidCoordinates.setText(QCoreApplication.translate("MainWindow", u"Centroid coordinates", None))
#if QT_CONFIG(tooltip)
        self.lb_Y.setToolTip(QCoreApplication.translate("MainWindow", u"Y coordinate of the centroid of the contoured object.", None))
#endif // QT_CONFIG(tooltip)
        self.lb_Y.setText(QCoreApplication.translate("MainWindow", u"Y", None))
#if QT_CONFIG(tooltip)
        self.pb_CentroidAuto.setToolTip(QCoreApplication.translate("MainWindow", u"Determines the coordinates of the contoured object centroid.", None))
#endif // QT_CONFIG(tooltip)
        self.pb_CentroidAuto.setText(QCoreApplication.translate("MainWindow", u"Auto", None))
#if QT_CONFIG(tooltip)
        self.le_CentroidY.setToolTip(QCoreApplication.translate("MainWindow", u"Y coordinate of the centroid of the contoured object.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.cb_MainSlice.setToolTip(QCoreApplication.translate("MainWindow", u"Slice with the largest contoured object.", None))
#endif // QT_CONFIG(tooltip)
        self.cb_MainSlice.setText(QCoreApplication.translate("MainWindow", u"Main Slice", None))
#if QT_CONFIG(tooltip)
        self.combob_cmap.setToolTip(QCoreApplication.translate("MainWindow", u"Choose display color map.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.lb_MapStats.setToolTip(QCoreApplication.translate("MainWindow", u"Displays heatmap stats: mean / median / min / max.", None))
#endif // QT_CONFIG(tooltip)
        self.lb_MapStats.setText(QCoreApplication.translate("MainWindow", u"Map stats", None))
#if QT_CONFIG(tooltip)
        self.lb_TargetStats.setToolTip(QCoreApplication.translate("MainWindow", u"Displays target stats: mean / median / min / max.", None))
#endif // QT_CONFIG(tooltip)
        self.lb_TargetStats.setText(QCoreApplication.translate("MainWindow", u"Target stats", None))
#if QT_CONFIG(tooltip)
        self.cb_SharedColorBar.setToolTip(QCoreApplication.translate("MainWindow", u"If checked, the colobars will have the same scale for all processed images.", None))
#endif // QT_CONFIG(tooltip)
        self.cb_SharedColorBar.setText(QCoreApplication.translate("MainWindow", u"Shared cb", None))
        self.combob_DensityDisplay.setItemText(0, QCoreApplication.translate("MainWindow", u"Percentage", None))
        self.combob_DensityDisplay.setItemText(1, QCoreApplication.translate("MainWindow", u"Count", None))
        self.combob_DensityDisplay.setItemText(2, QCoreApplication.translate("MainWindow", u"Count per 10k pixels", None))
        self.combob_DensityDisplay.setItemText(3, QCoreApplication.translate("MainWindow", u"Mean size", None))

#if QT_CONFIG(tooltip)
        self.combob_DensityDisplay.setToolTip(QCoreApplication.translate("MainWindow", u"Choose between the percentage of pixels with blobs , the count or the mean size of blobs.", None))
#endif // QT_CONFIG(tooltip)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), QCoreApplication.translate("MainWindow", u"Count", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Density", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Distance", None))
#if QT_CONFIG(tooltip)
        self.gb_ResultsChoice.setToolTip(QCoreApplication.translate("MainWindow", u"Select the results to save.", None))
#endif // QT_CONFIG(tooltip)
        self.gb_ResultsChoice.setTitle(QCoreApplication.translate("MainWindow", u"RESULT TYPES", None))
        self.cb_ResultsDistanceSpecificCentroid.setText(QCoreApplication.translate("MainWindow", u"Distance to centroid of main slice", None))
        self.cb_ResultsDensityCount.setText(QCoreApplication.translate("MainWindow", u"Density (count)", None))
        self.pb_ResultsNone.setText(QCoreApplication.translate("MainWindow", u"None", None))
        self.pb_ResultsAll.setText(QCoreApplication.translate("MainWindow", u"All", None))
        self.cb_ResultsCount.setText(QCoreApplication.translate("MainWindow", u"Count and size", None))
        self.cb_ResultsDistanceOwnCentroid.setText(QCoreApplication.translate("MainWindow", u"Distance to own centroid", None))
        self.cb_ResultsDensityPercentage.setText(QCoreApplication.translate("MainWindow", u"Density (percentage)", None))
        self.cb_ResultsDensitySize.setText(QCoreApplication.translate("MainWindow", u"Density (Size)", None))
#if QT_CONFIG(tooltip)
        self.pb_ResultsDestinationFolder.setToolTip(QCoreApplication.translate("MainWindow", u"Choose the destination folder to save the results.", None))
#endif // QT_CONFIG(tooltip)
        self.pb_ResultsDestinationFolder.setText(QCoreApplication.translate("MainWindow", u"Destination folder", None))
        self.lb_ResultsCSVFileName.setText(QCoreApplication.translate("MainWindow", u"Results file name (without .csv)", None))
#if QT_CONFIG(tooltip)
        self.le_ResultsCSVFileName.setToolTip(QCoreApplication.translate("MainWindow", u"Input a file name without extension.", None))
#endif // QT_CONFIG(tooltip)
        self.lb_ResultsDestinationFolder.setText("")
#if QT_CONFIG(tooltip)
        self.pb_ResultsBack.setToolTip(QCoreApplication.translate("MainWindow", u"Return to the images view.", None))
#endif // QT_CONFIG(tooltip)
        self.pb_ResultsBack.setText(QCoreApplication.translate("MainWindow", u"Back", None))
#if QT_CONFIG(tooltip)
        self.pb_ResultsSave.setToolTip(QCoreApplication.translate("MainWindow", u"Save the chosen Sresults.", None))
#endif // QT_CONFIG(tooltip)
        self.pb_ResultsSave.setText(QCoreApplication.translate("MainWindow", u"Save  results", None))
        self.menu_File.setTitle(QCoreApplication.translate("MainWindow", u"&Files", None))
        self.menu_Options.setTitle(QCoreApplication.translate("MainWindow", u"&Options", None))
        self.menu_About.setTitle(QCoreApplication.translate("MainWindow", u"&About", None))
        self.menu_Process.setTitle(QCoreApplication.translate("MainWindow", u"&Process", None))
    # retranslateUi

